### ISSUE TITLE
Licence des documents liés (images FunLab)

### ISSUE THREAD

**Issue by Rom1deTroyes** [RomainLalande/fiches_peda_fablabs#2]
Le Bonjour !

Sur la fiche, il est précisé `Fiche placée sous licence CC by SA`, ça couvre donc le texte du fichier, mais pas les images utilisées, qui sont des liens externes.

Par exemple, l'image illustrant l'atelier Arduino :

 ![photo_atelier](http://wiki.funlab.fr/images/thumb/c/c1/Ados_arduino_3.jpg/800px-Ados_arduino_3.jpg)

C'est un lien vers le wiki FunLab qui affiche dans le navigateur une image dont la licence n'est pas apposée sur le site cible (voir http://wiki.funlab.fr/index.php/Fichier:Ados_arduino_3.jpg)

... Du coup, la fiche n'est pas réutilisable telle quelle !

Du coup :
- Soit l'auteur des images dépose une copie dans le dépôt et y appose une licence (idéalement la même que pour les fiches :-) 
- Soit il faut imposer que les images liées soient compatible avec la licence utilisée
- Soit on précise que la licence ne concerne pas les ressources externes (mais c'est dommage !)

**Comment by RomainLalande** [comment]
Hello, merci pour le retour, il faut que je finisse avec les image, c'est clair ! 
Il n'y en a qu'une qui ne respecte pas le CC by SA mais je pense que je vais mettre les autres en CC0. 
Je ferai une MàJ de la fiche dés que ce serai fait ! 
Mais je me pose une question suite à ton message : on peut uploader des images pour les héberger sur le dépôt github ? Ça simplifierait beaucoup la tâche...
C'est cool d'avoir un feedback, et ça donne envie de fignoler du coup :-)
Romain

**Comment by RomainLalande** [comment]
Bon, du coup comme c'était un peu laborieux avec mediawiki (obligé de ré-uploader toutes les images pour préciser la licence), j'ai préféré tout passer en CC0 celles qui viennent de moi, et j'ai enlevé la photo qui n'était pas de moi. Je ferai plus sérieusement cette partie la prochaine fois !
